# # version: '3'
# services:
#   pgvector:
#     image: ankane/pgvector:latest
#     restart: always
#     environment:
#       POSTGRES_DB: makronexus
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: E1a2g3l4e!
#     ports:
#       - "5432:5432"
#     volumes:
#       - ~/volumes/pgvector:/var/lib/postgresql/data
